before_install:
 - gem update --system
 - gem install bundler
bundler_args: --without development
language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
 - 2.1.10
 - 2.2.10
 - 2.3.7
 - 2.4.4
 - 2.5.1
 - ruby-head
matrix:
  allow_failures:
   - rvm: ruby-head
  fast_finish: true
script: bundle exec brownie spec
sudo: false
cache: bundler
